### ISSUE TITLE
Descripition spells on iOS

### ISSUE THREAD

**Issue by burukabrk** [krosmaker/krosmaker#84]
On iOS, the description of the spells does not appear, and it is not even possible to add icons.

**Comment by czyzby** [comment]
Hey @burukabrk, thanks for raising the issue. Unfortunately, mobile browsers are not supported by Krosmaker at all, and likely never will be for a number of reasons. The user interface would have to be redesigned and retested to support different resolutions. Crucial features like image cropping or card saving and export are not guaranteed to work on mobile due to lack of support for certain browser features or libraries.

I had a colleague test the application on an iMac. Safari didn't export the card images correctly, but Chrome seems to support all Krosmaker features. If you're on an iPad, perhaps you could try using Google Chrome to see if it helps.

I could look into a simplified mobile version, perhaps with much less features, but honestly I'm not sure it's worth the effort given the state of the franchise. For now, please use the desktop version.
